#!/usr/bin/env bash
# =============================================================================
# FR-01: Account Registration — API & DB Test Suite
# Generated by: test-execution-assistant skill
# Run from: eshop-sut/ root directory
# Usage:    bash scripts/curl/FR01-api-tests.sh
# Evidence: evidence/api-responses/FR01/
# Requires: curl, python3, sqlite3
# =============================================================================

set -uo pipefail

BASE_URL="http://localhost:3000"
DB="backend/database.sqlite"
RESP_DIR="evidence/api-responses/FR01"
mkdir -p "$RESP_DIR"

# Counters and result accumulator
PASS=0; FAIL=0; SKIP=0
declare -a SUMMARY_ROWS=()

# TC Context Variables
CURRENT_TC_ID=""
CURRENT_TC_FAIL=0
CURRENT_TC_DESC=""
CURRENT_TC_EXP=""
CURRENT_TC_ACT=""

# Color codes
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m';  BOLD='\033[1m';   NC='\033[0m'

# ── Preflight checks ──────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Preflight checks...${NC}"
[[ ! -f "$DB" ]] && echo -e "${RED}ERROR: Database not found at $DB${NC}" && exit 1
curl -sf "$BASE_URL/api/products" > /dev/null \
  || { echo -e "${RED}ERROR: Backend not responding at $BASE_URL${NC}"; exit 1; }
command -v sqlite3 > /dev/null \
  || { echo -e "${RED}ERROR: sqlite3 not installed${NC}"; exit 1; }
echo -e "${GREEN}All systems ready.${NC}\n"

# ── Token Setup ───────────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Acquiring tokens...${NC}"

USER_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"test@eshop.com","password":"Test1234!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

ADMIN_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@eshop.com","password":"Admin123!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

[[ "$USER_TOKEN"  == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get user token${NC}"  && exit 1
[[ "$ADMIN_TOKEN" == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get admin token${NC}" && exit 1
echo -e "${GREEN}Tokens acquired.${NC}\n"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

start_tc() {
  CURRENT_TC_ID="$1"
  CURRENT_TC_FAIL=0
  CURRENT_TC_DESC=""
  CURRENT_TC_EXP=""
  CURRENT_TC_ACT=""
}

end_tc() {
  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    ((PASS++))
    SUMMARY_ROWS+=("PASS|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  else
    ((FAIL++))
    SUMMARY_ROWS+=("FAIL|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  fi
}

run_and_assert() {
  local TC_ID="$1" EXPECTED="$2" METHOD="$3" ENDPOINT="$4" TOKEN="$5"
  local BODY="${6:-}"
  local RESP_FILE="$RESP_DIR/${TC_ID}-response.json"

  local CURL_CMD=(curl -s -o "$RESP_FILE" -w "%{http_code}" -X "$METHOD" "${BASE_URL}${ENDPOINT}" -H "Content-Type: application/json")
  if [[ "$TOKEN" == "user" ]]; then CURL_CMD+=(-H "Authorization: Bearer $USER_TOKEN"); fi
  if [[ "$TOKEN" == "admin" ]]; then CURL_CMD+=(-H "Authorization: Bearer $ADMIN_TOKEN"); fi
  if [[ -n "$BODY" ]]; then CURL_CMD+=(-d "$BODY"); fi

  local ACTUAL
  ACTUAL=$("${CURL_CMD[@]}" 2>/dev/null)

  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  local STATUS COLOR
  if [[ "$ACTUAL" == "$EXPECTED" ]]; then 
    STATUS="PASS"; COLOR="$GREEN"
  else                                   
    STATUS="FAIL"; COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${BOLD}${TC_ID}${NC} — HTTP ${ACTUAL} (expected ${EXPECTED})"
  [[ "$STATUS" == "FAIL" ]] && \
    python3 -m json.tool "$RESP_FILE" 2>/dev/null | sed 's/^/        /' || true
  echo ""
}

assert_json_field() {
  local TC_ID="$1" RESP_FILE="$2" FIELD="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(python3 -c "
import json, sys
try:
    d = json.load(open('$RESP_FILE'))
    v = d.get('$FIELD', '__MISSING__')
    print(str(v))
except Exception as e:
    print('__ERROR__:' + str(e))
" 2>/dev/null)

  if   [[ "$EXPECTED" == "EXISTS"       && "$ACTUAL" != "__MISSING__" && "$ACTUAL" != __ERROR__* ]]; then
       STATUS="PASS"
  elif [[ "$EXPECTED" == "POSITIVE_INT" ]] && python3 -c "v=int('$ACTUAL'); exit(0 if v>0 else 1)" 2>/dev/null; then
       STATUS="PASS"
  elif [[ "$EXPECTED" != "EXISTS" && "$EXPECTED" != "POSITIVE_INT" && "$ACTUAL" == "$EXPECTED" ]]; then
       STATUS="PASS"
  else 
       STATUS="FAIL"
  fi

  if [[ "$STATUS" == "PASS" ]]; then
    COLOR="$GREEN"
  else
    COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="json[$FIELD]"
    CURRENT_TC_EXP="$EXPECTED"
    CURRENT_TC_ACT="${ACTUAL:0:25}"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — field '${FIELD}': expected=${EXPECTED}, actual=${ACTUAL}"
}

assert_db() {
  local TC_ID="$1" DESC="$2" SQL="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(sqlite3 "$DB" "$SQL" 2>/dev/null)

  case "$EXPECTED" in
    EXISTS) [[ -n "$ACTUAL" ]]         && STATUS="PASS" || STATUS="FAIL" ;;
    EMPTY)  [[ -z "$ACTUAL" ]]         && STATUS="PASS" || STATUS="FAIL" ;;
    BCRYPT) [[ "$ACTUAL" == \$2* ]]    && STATUS="PASS" || STATUS="FAIL" ;;
    *)      [[ "$ACTUAL" == "$EXPECTED" ]] && STATUS="PASS" || STATUS="FAIL" ;;
  esac

  if [[ "$STATUS" == "PASS" ]]; then
    COLOR="$GREEN"
  else
    COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="DB: $DESC"
    CURRENT_TC_EXP="$EXPECTED"
    CURRENT_TC_ACT="${ACTUAL:-<empty>}"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — DB: ${DESC}"
  echo -e "       SQL:      ${SQL}"
  echo -e "       Expected: ${EXPECTED} | Actual: ${ACTUAL:-<empty>}"
  echo ""
}

teardown_db() {
  local DESC="$1" SQL="$2"
  echo -e "${YELLOW}[TEARDOWN]${NC} $DESC"
  sqlite3 "$DB" "$SQL" 2>/dev/null \
    && echo -e "  ${GREEN}Done${NC}" \
    || echo -e "  ${YELLOW}Nothing to delete (OK if TC was expected to fail)${NC}"
  echo ""
}

# =============================================================================
# TEST CASES
# =============================================================================
# ── FR01-EP-001: Verify user registration succeeds with all valid name, email, and strong password inputs ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-001: API ===${NC}"
start_tc "FR01-EP-001"
run_and_assert "FR01-EP-001" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep001@test.com","password":"Test@123"}'
assert_json_field "FR01-EP-001-msg" "$RESP_DIR/FR01-EP-001-response.json" "message" "User registered successfully"
assert_json_field "FR01-EP-001-id" "$RESP_DIR/FR01-EP-001-response.json" "id" "POSITIVE_INT"
assert_db "FR01-EP-001-exists" "User row exists" "SELECT email FROM users WHERE email='ep001@test.com';" "ep001@test.com"
assert_db "FR01-EP-001-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='ep001@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='ep001@test.com';"
end_tc

# ── FR01-EP-002: Verify user registration rejects submission when the name field is empty ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-002: API ===${NC}"
start_tc "FR01-EP-002"
run_and_assert "FR01-EP-002" "400" "POST" "/api/register" "none" '{"name":"","email":"ep002@test.com","password":"Test@123"}'
end_tc

# ── FR01-EP-003: Verify registration API rejects request with name field absent from JSON body ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-003: API ===${NC}"
start_tc "FR01-EP-003"
run_and_assert "FR01-EP-003" "400" "POST" "/api/register" "none" '{"email":"ep003@test.com","password":"Test@123"}'
end_tc

# ── FR01-EP-004: Verify user registration rejects email that does not contain an @ symbol ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-004: API ===${NC}"
start_tc "FR01-EP-004"
run_and_assert "FR01-EP-004" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"invalidemail","password":"Test@123"}'
end_tc

# ── FR01-EP-005: Verify user registration rejects email with no domain part after the @ symbol ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-005: API ===${NC}"
start_tc "FR01-EP-005"
run_and_assert "FR01-EP-005" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"user@","password":"Test@123"}'
end_tc

# ── FR01-EP-006: Verify user registration rejects email with no local part before the @ symbol ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-006: API ===${NC}"
start_tc "FR01-EP-006"
run_and_assert "FR01-EP-006" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"@domain.com","password":"Test@123"}'
end_tc

# ── FR01-EP-007: Verify user registration rejects email that is already registered in the system ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-007: API ===${NC}"
start_tc "FR01-EP-007"
run_and_assert "FR01-EP-007" "409" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"test@eshop.com","password":"Test@123"}'
end_tc

# ── FR01-EP-008: Verify user registration rejects submission when the email field is empty ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-008: API ===${NC}"
start_tc "FR01-EP-008"
run_and_assert "FR01-EP-008" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"","password":"Test@123"}'
end_tc

# ── FR01-EP-009: Verify registration API rejects request with email field absent from JSON body ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-009: API ===${NC}"
start_tc "FR01-EP-009"
run_and_assert "FR01-EP-009" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","password":"Test@123"}'
end_tc

# ── FR01-EP-010: Verify user registration rejects password shorter than the minimum required 8 characters ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-010: API ===${NC}"
start_tc "FR01-EP-010"
run_and_assert "FR01-EP-010" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep010@test.com","password":"Te@1"}'
end_tc

# ── FR01-EP-011: Verify user registration rejects password that contains no uppercase letter ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-011: API ===${NC}"
start_tc "FR01-EP-011"
run_and_assert "FR01-EP-011" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep011@test.com","password":"test@123"}'
end_tc

# ── FR01-EP-012: Verify user registration rejects password that contains no lowercase letter ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-012: API ===${NC}"
start_tc "FR01-EP-012"
run_and_assert "FR01-EP-012" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep012@test.com","password":"TEST@123"}'
end_tc

# ── FR01-EP-013: Verify user registration rejects password that contains no numeric digit ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-013: API ===${NC}"
start_tc "FR01-EP-013"
run_and_assert "FR01-EP-013" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep013@test.com","password":"Test@abc"}'
end_tc

# ── FR01-EP-014: Verify user registration rejects password that contains no special character at all ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-014: API ===${NC}"
start_tc "FR01-EP-014"
run_and_assert "FR01-EP-014" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep014@test.com","password":"Test1234"}'
end_tc

# ── FR01-EP-015: Verify user registration rejects password containing a special character outside the allowed set `@$!%*?&` ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-015: API ===${NC}"
start_tc "FR01-EP-015"
run_and_assert "FR01-EP-015" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep015@test.com","password":"Test#123"}'
end_tc

# ── FR01-EP-016: Verify user registration rejects submission when the password field is empty ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-016: API ===${NC}"
start_tc "FR01-EP-016"
run_and_assert "FR01-EP-016" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep016@test.com","password":""}'
end_tc

# ── FR01-EP-017: Verify registration API rejects request with password field absent from JSON body ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-017: API ===${NC}"
start_tc "FR01-EP-017"
run_and_assert "FR01-EP-017" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"ep017@test.com"}'
end_tc

# ── FR01-EP-020: Verify registration accepts name containing XSS payload and renders it safely on UI without script execution ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-EP-020: API ===${NC}"
start_tc "FR01-EP-020"
run_and_assert "FR01-EP-020" "200" "POST" "/api/register" "none" '{"name": "<script>alert(1)</script>", "email": "ep020@test.com", "password": "Test@123"}'
assert_json_field "FR01-EP-020-msg" "$RESP_DIR/FR01-EP-020-response.json" "message" "User registered successfully"
assert_json_field "FR01-EP-020-id" "$RESP_DIR/FR01-EP-020-response.json" "id" "POSITIVE_INT"
assert_db "FR01-EP-020-exists" "User row exists" "SELECT email FROM users WHERE email='ep020@test.com';" "ep020@test.com"
assert_db "FR01-EP-020-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='ep020@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='ep020@test.com';"
end_tc

# ── FR01-BVA-001: Verify user registration rejects password at absolute minimum length (0 chars — empty string) ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-001: API ===${NC}"
start_tc "FR01-BVA-001"
run_and_assert "FR01-BVA-001" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva001@test.com","password":""}'
end_tc

# ── FR01-BVA-002: Verify user registration rejects password of exactly 7 characters, one below the minimum required length of 8 ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-002: API ===${NC}"
start_tc "FR01-BVA-002"
run_and_assert "FR01-BVA-002" "400" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva002@test.com","password":"Te@1aBc"}'
end_tc

# ── FR01-BVA-003: Verify user registration accepts password of exactly 8 characters at the lower boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-003: API ===${NC}"
start_tc "FR01-BVA-003"
run_and_assert "FR01-BVA-003" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva003@test.com","password":"Test@123"}'
assert_json_field "FR01-BVA-003-msg" "$RESP_DIR/FR01-BVA-003-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-003-id" "$RESP_DIR/FR01-BVA-003-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-003-exists" "User row exists" "SELECT email FROM users WHERE email='bva003@test.com';" "bva003@test.com"
assert_db "FR01-BVA-003-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva003@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva003@test.com';"
end_tc

# ── FR01-BVA-004: Verify user registration accepts password of 9 characters, one above the lower boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-004: API ===${NC}"
start_tc "FR01-BVA-004"
run_and_assert "FR01-BVA-004" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva004@test.com","password":"Test@1234"}'
assert_json_field "FR01-BVA-004-msg" "$RESP_DIR/FR01-BVA-004-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-004-id" "$RESP_DIR/FR01-BVA-004-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-004-exists" "User row exists" "SELECT email FROM users WHERE email='bva004@test.com';" "bva004@test.com"
assert_db "FR01-BVA-004-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva004@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva004@test.com';"
end_tc

# ── FR01-BVA-005: Verify user registration accepts password of 15 characters at nominal length ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-005: API ===${NC}"
start_tc "FR01-BVA-005"
run_and_assert "FR01-BVA-005" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva005@test.com","password":"TestPassw0rd!Ab"}'
assert_json_field "FR01-BVA-005-msg" "$RESP_DIR/FR01-BVA-005-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-005-id" "$RESP_DIR/FR01-BVA-005-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-005-exists" "User row exists" "SELECT email FROM users WHERE email='bva005@test.com';" "bva005@test.com"
assert_db "FR01-BVA-005-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva005@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva005@test.com';"
end_tc

# ── FR01-BVA-006: Verify system behavior when password reaches absolute maximum length of 300 characters ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-006: API ===${NC}"
start_tc "FR01-BVA-006"
run_and_assert "FR01-BVA-006" "400" "POST" "/api/register" "none" '{"name": "Nguyen Van A", "email": "bva006@test.com", "password": "Aa1@'"$(printf 'A%.0s' {1..296})"'"}'
end_tc

# ── FR01-BVA-007: Verify user registration rejects name at absolute minimum length (0 chars — empty string) ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-007: API ===${NC}"
start_tc "FR01-BVA-007"
run_and_assert "FR01-BVA-007" "400" "POST" "/api/register" "none" '{"name":"","email":"bva007@test.com","password":"Test@123"}'
end_tc

# ── FR01-BVA-008: Verify user registration accepts name of exactly 1 character at the lower boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-008: API ===${NC}"
start_tc "FR01-BVA-008"
run_and_assert "FR01-BVA-008" "200" "POST" "/api/register" "none" '{"name":"A","email":"bva008@test.com","password":"Test@123"}'
assert_json_field "FR01-BVA-008-msg" "$RESP_DIR/FR01-BVA-008-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-008-id" "$RESP_DIR/FR01-BVA-008-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-008-exists" "User row exists" "SELECT email FROM users WHERE email='bva008@test.com';" "bva008@test.com"
assert_db "FR01-BVA-008-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva008@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva008@test.com';"
end_tc

# ── FR01-BVA-009: Verify user registration accepts name of 2 characters, one above the lower boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-009: API ===${NC}"
start_tc "FR01-BVA-009"
run_and_assert "FR01-BVA-009" "200" "POST" "/api/register" "none" '{"name":"AB","email":"bva009@test.com","password":"Test@123"}'
assert_json_field "FR01-BVA-009-msg" "$RESP_DIR/FR01-BVA-009-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-009-id" "$RESP_DIR/FR01-BVA-009-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-009-exists" "User row exists" "SELECT email FROM users WHERE email='bva009@test.com';" "bva009@test.com"
assert_db "FR01-BVA-009-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva009@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva009@test.com';"
end_tc

# ── FR01-BVA-010: Verify user registration accepts name of 12 characters at nominal length ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-010: API ===${NC}"
start_tc "FR01-BVA-010"
run_and_assert "FR01-BVA-010" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"bva010@test.com","password":"Test@123"}'
assert_json_field "FR01-BVA-010-msg" "$RESP_DIR/FR01-BVA-010-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-010-id" "$RESP_DIR/FR01-BVA-010-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-010-exists" "User row exists" "SELECT email FROM users WHERE email='bva010@test.com';" "bva010@test.com"
assert_db "FR01-BVA-010-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva010@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva010@test.com';"
end_tc

# ── FR01-BVA-011: Verify user registration accepts name of 254 characters, one below the assumed DB VARCHAR upper limit ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-011: API ===${NC}"
start_tc "FR01-BVA-011"
run_and_assert "FR01-BVA-011" "200" "POST" "/api/register" "none" '{"name": "'"$(printf 'A%.0s' {1..254})"'", "email": "bva011@test.com", "password": "Test@123"}'
assert_json_field "FR01-BVA-011-msg" "$RESP_DIR/FR01-BVA-011-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-011-id" "$RESP_DIR/FR01-BVA-011-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-011-exists" "User row exists" "SELECT email FROM users WHERE email='bva011@test.com';" "bva011@test.com"
assert_db "FR01-BVA-011-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva011@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva011@test.com';"
end_tc

# ── FR01-BVA-012: Verify user registration accepts name of 255 characters at the assumed DB VARCHAR upper boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-012: API ===${NC}"
start_tc "FR01-BVA-012"
run_and_assert "FR01-BVA-012" "200" "POST" "/api/register" "none" '{"name": "'"$(printf 'A%.0s' {1..255})"'", "email": "bva012@test.com", "password": "Test@123"}'
assert_json_field "FR01-BVA-012-msg" "$RESP_DIR/FR01-BVA-012-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-012-id" "$RESP_DIR/FR01-BVA-012-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-012-exists" "User row exists" "SELECT email FROM users WHERE email='bva012@test.com';" "bva012@test.com"
assert_db "FR01-BVA-012-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='bva012@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='bva012@test.com';"
end_tc

# ── FR01-BVA-013: Verify system behavior when name exceeds the assumed DB VARCHAR limit by 1 character ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-013: API ===${NC}"
start_tc "FR01-BVA-013"
run_and_assert "FR01-BVA-013" "400" "POST" "/api/register" "none" '{"name": "'"$(printf 'A%.0s' {1..256})"'", "email": "bva013@test.com", "password": "Test@123"}'
end_tc

# ── FR01-BVA-014: Verify system behavior when name reaches absolute system maximum of 500 characters ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-014: API ===${NC}"
start_tc "FR01-BVA-014"
run_and_assert "FR01-BVA-014" "400" "POST" "/api/register" "none" '{"name": "'"$(printf 'A%.0s' {1..500})"'", "email": "bva014@test.com", "password": "Test@123"}'
end_tc

# ── FR01-BVA-015: Verify user registration accepts email of 16 characters at nominal length ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-015: API ===${NC}"
start_tc "FR01-BVA-015"
run_and_assert "FR01-BVA-015" "200" "POST" "/api/register" "none" '{"name":"Nguyen Van A","email":"newuser@test.com","password":"Test@123"}'
assert_json_field "FR01-BVA-015-msg" "$RESP_DIR/FR01-BVA-015-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-015-id" "$RESP_DIR/FR01-BVA-015-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-015-exists" "User row exists" "SELECT email FROM users WHERE email='newuser@test.com';" "newuser@test.com"
assert_db "FR01-BVA-015-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='newuser@test.com';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='newuser@test.com';"
end_tc

# ── FR01-BVA-016: Verify user registration accepts email of 255 characters at the assumed DB VARCHAR upper boundary ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-016: API ===${NC}"
start_tc "FR01-BVA-016"
LONG_EMAIL_016="$(printf 'a%.0s' {1..246})@test.com"
run_and_assert "FR01-BVA-016" "200" "POST" "/api/register" "none" '{"name": "Nguyen Van A", "email": "'"$LONG_EMAIL_016"'", "password": "Test@123"}'
assert_json_field "FR01-BVA-016-msg" "$RESP_DIR/FR01-BVA-016-response.json" "message" "User registered successfully"
assert_json_field "FR01-BVA-016-id" "$RESP_DIR/FR01-BVA-016-response.json" "id" "POSITIVE_INT"
assert_db "FR01-BVA-016-exists" "User row exists" "SELECT email FROM users WHERE email='$LONG_EMAIL_016';" "$LONG_EMAIL_016"
assert_db "FR01-BVA-016-hash" "Password is bcrypt-hashed" "SELECT password FROM users WHERE email='$LONG_EMAIL_016';" "BCRYPT"
teardown_db "Delete test user" "DELETE FROM users WHERE email='$LONG_EMAIL_016';"
end_tc

# ── FR01-BVA-017: Verify system behavior when email exceeds the assumed DB VARCHAR limit by 1 character ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-017: API ===${NC}"
start_tc "FR01-BVA-017"
LONG_EMAIL_017="$(printf 'a%.0s' {1..247})@test.com"
run_and_assert "FR01-BVA-017" "400" "POST" "/api/register" "none" '{"name": "Nguyen Van A", "email": "'"$LONG_EMAIL_017"'", "password": "Test@123"}'
end_tc

# ── FR01-BVA-018: Verify system behavior when email reaches absolute system maximum of 300 characters ─────────────────────────────────────────────
echo -e "${CYAN}=== FR01-BVA-018: API ===${NC}"
start_tc "FR01-BVA-018"
LONG_EMAIL_018="$(printf 'a%.0s' {1..291})@test.com"
run_and_assert "FR01-BVA-018" "400" "POST" "/api/register" "none" '{"name": "Nguyen Van A", "email": "'"$LONG_EMAIL_018"'", "password": "Test@123"}'
end_tc

# =============================================================================
# FINAL SUMMARY
# =============================================================================
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} FR-01 TEST RESULTS — AUTOMATED CHECKS${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
printf "  %-20s %-35s %-35s %s\n" "TC ID / Check" "Expected" "Actual" "Status"
echo "  ──────────────────────────────────────────────────────────────────"
for row in "${SUMMARY_ROWS[@]}"; do
  IFS='|' read -r S ID EP ACT <<< "$row"
  [[ "$S" == "PASS" ]] && C="$GREEN" || C="$RED"
  printf "  ${C}%-20s %-35s %-35s %s${NC}\n" \
    "${ID:0:20}" "${EP:0:35}" "${ACT:0:35}" "$S"
done
echo "  ──────────────────────────────────────────────────────────────────"
echo -e "  ${BOLD}TOTAL (automated): ${GREEN}${PASS} PASS${NC} | ${RED}${FAIL} FAIL${NC} | ${YELLOW}${SKIP} SKIP${NC}"
echo ""
echo -e "${YELLOW}  Still requires manual testing:${NC}"
echo -e "    UI-only TCs : FR01-EP-018, FR01-EP-019 → open http://localhost:5173/register"
echo -e "    DOM checks  : paste scripts/curl/FR01-dom-checks.js into DevTools"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Response JSON files saved to: $RESP_DIR/"
echo "Paste the summary block above into Phase B prompt."
