#!/usr/bin/env bash
# =============================================================================
# FR-03: Forgot Password & Reset Password (Mobile) — API & DB Test Suite
# Generated by: test-execution-assistant skill
# Run from:     eshop-sut/ root directory
# Usage:        bash scripts/curl/FR03-api-tests.sh
# Evidence:     evidence/api-responses/FR03/
# Requires:     curl, python3, sqlite3
# =============================================================================

set -uo pipefail

BASE_URL="http://localhost:3000"
DB="backend/database.sqlite"
RESP_DIR="evidence/api-responses/FR03"
mkdir -p "$RESP_DIR"

# Counters and result accumulator
PASS=0; FAIL=0; SKIP=0
declare -a SUMMARY_ROWS=()

# TC Context Variables
CURRENT_TC_ID=""
CURRENT_TC_FAIL=0
CURRENT_TC_DESC=""
CURRENT_TC_EXP=""
CURRENT_TC_ACT=""

# Color codes
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m';  BOLD='\033[1m';   NC='\033[0m'

# ── Preflight checks ──────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Preflight checks...${NC}"
[[ ! -f "$DB" ]] && echo -e "${RED}ERROR: Database not found at $DB${NC}" && exit 1
command -v sqlite3 > /dev/null || { echo -e "${RED}ERROR: sqlite3 not installed${NC}"; exit 1; }
echo -e "${GREEN}All systems ready.${NC}\n"

# ── Helper Functions ──────────────────────────────────────────────────────────

start_tc() {
  CURRENT_TC_ID="$1"
  CURRENT_TC_FAIL=0
  CURRENT_TC_DESC=""
  CURRENT_TC_EXP=""
  CURRENT_TC_ACT=""
}

end_tc() {
  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    ((PASS++))
    SUMMARY_ROWS+=("PASS|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  else
    ((FAIL++))
    SUMMARY_ROWS+=("FAIL|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  fi
}

run_and_assert() {
  local TC_ID="$1" EXPECTED="$2" METHOD="$3" ENDPOINT="$4" TOKEN="$5"
  local BODY="${6:-}"
  local RESP_FILE="$RESP_DIR/${TC_ID}-response.json"

  local CURL_CMD=(curl -s -o "$RESP_FILE" -w "%{http_code}" -X "$METHOD" "${BASE_URL}${ENDPOINT}" -H "Content-Type: application/json")
  if [[ -n "$BODY" ]]; then CURL_CMD+=(-d "$BODY"); fi

  local ACTUAL
  ACTUAL=$("${CURL_CMD[@]}" 2>/dev/null)

  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  local STATUS COLOR
  if [[ "$ACTUAL" == "$EXPECTED" ]] || [[ "$EXPECTED" == *"/"* && "$EXPECTED" == *"$ACTUAL"* ]]; then
    STATUS="PASS"; COLOR="$GREEN"
  else
    STATUS="FAIL"; COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${BOLD}${TC_ID}${NC} — HTTP ${ACTUAL} (expected ${EXPECTED})"
  [[ "$STATUS" == "FAIL" ]] && python3 -m json.tool "$RESP_FILE" 2>/dev/null | sed 's/^/        /' || true
}

assert_db() {
  local TC_ID="$1" DESC="$2" SQL="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(sqlite3 "$DB" "$SQL" 2>/dev/null)

  case "$EXPECTED" in
    EXISTS) [[ -n "$ACTUAL" ]]         && STATUS="PASS" || STATUS="FAIL" ;;
    EMPTY)  [[ -z "$ACTUAL" ]]         && STATUS="PASS" || STATUS="FAIL" ;;
    BCRYPT) [[ "$ACTUAL" == \$2* ]]    && STATUS="PASS" || STATUS="FAIL" ;;
    *)      [[ "$ACTUAL" == "$EXPECTED" ]] && STATUS="PASS" || STATUS="FAIL" ;;
  esac

  if [[ "$STATUS" == "PASS" ]]; then
    COLOR="$GREEN"
  else
    COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="DB: $DESC"
    CURRENT_TC_EXP="$EXPECTED"
    CURRENT_TC_ACT="${ACTUAL:-<empty>}"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — DB: ${DESC}"
}

get_otp() {
  local EMAIL="$1"
  curl -s -X POST "$BASE_URL/api/forgot-password" \
    -H "Content-Type: application/json" \
    -d '{"email":"'"$EMAIL"'"}' \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('resetToken', ''))" 2>/dev/null
}

# Preserve the original hash for teardown
ORIGINAL_HASH=$(sqlite3 "$DB" "SELECT password FROM users WHERE email='test@eshop.com';")

# =============================================================================
# TEST EXECUTIONS
# =============================================================================

# ── FR03-EP-001: Happy Path ──────────────────────────────────────────────────
echo -e "\n${CYAN}=== FR03-EP-001: Happy Path ===${NC}"
start_tc "FR03-EP-001"
OTP=$(get_otp "test@eshop.com")
if [[ -z "$OTP" ]]; then
  echo -e "${RED}ERROR: Failed to obtain OTP for test@eshop.com${NC}"
  CURRENT_TC_FAIL=1
else
  run_and_assert "FR03-EP-001" "200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'
  assert_db "FR03-EP-001-db-hash" "Password is bcrypt hashed" "SELECT password FROM users WHERE email='test@eshop.com';" "BCRYPT"
  assert_db "FR03-EP-001-db-otp" "OTP marked as used or deleted" "SELECT reset_token FROM users WHERE email='test@eshop.com';" "EMPTY"
fi
# Teardown
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"
end_tc

# ── FR03-EP-002 to 007: Forgot Password API Failures ─────────────────────────
echo -e "\n${CYAN}=== FR03-EP-002 to 007: Forgot Password API Failures ===${NC}"
start_tc "FR03-EP-002"; run_and_assert "FR03-EP-002" "400" "POST" "/api/forgot-password" "none" '{"email":"invalidemail"}'; end_tc
start_tc "FR03-EP-003"; run_and_assert "FR03-EP-003" "400" "POST" "/api/forgot-password" "none" '{"email":"user@"}'; end_tc
start_tc "FR03-EP-004"; run_and_assert "FR03-EP-004" "400" "POST" "/api/forgot-password" "none" '{"email":"@domain.com"}'; end_tc
start_tc "FR03-EP-005"; run_and_assert "FR03-EP-005" "404" "POST" "/api/forgot-password" "none" '{"email":"unknown@eshop.com"}'; end_tc
start_tc "FR03-EP-006"; run_and_assert "FR03-EP-006" "400" "POST" "/api/forgot-password" "none" '{"email":""}'; end_tc
start_tc "FR03-EP-007"; run_and_assert "FR03-EP-007" "400" "POST" "/api/forgot-password" "none" '{}'; end_tc

# ── FR03-EP-008 to 013: Reset Password Email Mismatches / Failures ───────────
echo -e "\n${CYAN}=== FR03-EP-008 to 013: Reset Password Email Mismatches / Failures ===${NC}"
OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-008"; run_and_assert "FR03-EP-008" "400/403" "POST" "/api/reset-password" "none" '{"email":"different@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-009"; run_and_assert "FR03-EP-009" "400" "POST" "/api/reset-password" "none" '{"email":"invalidemail","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-010"; run_and_assert "FR03-EP-010" "400" "POST" "/api/reset-password" "none" '{"email":"user@","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-011"; run_and_assert "FR03-EP-011" "400" "POST" "/api/reset-password" "none" '{"email":"@domain.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-012"; run_and_assert "FR03-EP-012" "400" "POST" "/api/reset-password" "none" '{"email":"","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-013"; run_and_assert "FR03-EP-013" "400" "POST" "/api/reset-password" "none" '{"resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

# ── FR03-EP-014 to 017: OTP Failures ─────────────────────────────────────────
echo -e "\n${CYAN}=== FR03-EP-014 to 017: OTP Failures ===${NC}"
start_tc "FR03-EP-014"; run_and_assert "FR03-EP-014" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"999999","newPassword":"Test@123"}'; end_tc

# Cross email
OTP=$(get_otp "admin@eshop.com")
start_tc "FR03-EP-015"; run_and_assert "FR03-EP-015" "400/403" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

# Reuse Attempt
OTP=$(get_otp "test@eshop.com")
curl -s -X POST "$BASE_URL/api/reset-password" -H "Content-Type: application/json" -d '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}' > /dev/null
start_tc "FR03-EP-016"; run_and_assert "FR03-EP-016" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

# Expired OTP
OTP=$(get_otp "test@eshop.com")
echo -e "${YELLOW}Waiting 60 seconds to test OTP expiration (FR03-EP-017)...${NC}"
sleep 60
start_tc "FR03-EP-017"; run_and_assert "FR03-EP-017" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc

# ── FR03-EP-018 to 029: OTP Length, Password Length, & Strength ──────────────
echo -e "\n${CYAN}=== FR03-EP-018 to 029: OTP Length, Password Length, & Strength ===${NC}"
start_tc "FR03-EP-018"; run_and_assert "FR03-EP-018" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"12345","newPassword":"Test@123"}'; end_tc

start_tc "FR03-EP-019"; run_and_assert "FR03-EP-019" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"1234567","newPassword":"Test@123"}'; end_tc

start_tc "FR03-EP-020"; run_and_assert "FR03-EP-020" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"","newPassword":"Test@123"}'; end_tc

start_tc "FR03-EP-021"; run_and_assert "FR03-EP-021" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-022"; run_and_assert "FR03-EP-022" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Te@1"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-023"; run_and_assert "FR03-EP-023" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-024"; run_and_assert "FR03-EP-024" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"TEST@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-025"; run_and_assert "FR03-EP-025" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@abc"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-026"; run_and_assert "FR03-EP-026" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test1234"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-027"; run_and_assert "FR03-EP-027" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test#123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-028"; run_and_assert "FR03-EP-028" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":""}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-EP-029"; run_and_assert "FR03-EP-029" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'"}'; end_tc

sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

# ── FR03-BVA ─────────────────────────────────────────────────────────────────
echo -e "\n${CYAN}=== FR03-BVA: Boundary Value Analysis ===${NC}"
OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-001"; run_and_assert "FR03-BVA-001" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":""}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-002"; run_and_assert "FR03-BVA-002" "400" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@12"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-003"; run_and_assert "FR03-BVA-003" "200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-004"; run_and_assert "FR03-BVA-004" "200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@1234"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-005"; run_and_assert "FR03-BVA-005" "200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"TestPassword12!"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

OTP=$(get_otp "test@eshop.com")
VLONG_PASS="T$(printf 'e%.0s' {1..290})st@123"
start_tc "FR03-BVA-006"; run_and_assert "FR03-BVA-006" "400/500/200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"'"$VLONG_PASS"'"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

start_tc "FR03-BVA-007"; run_and_assert "FR03-BVA-007" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"","newPassword":"Test@123"}'; end_tc
start_tc "FR03-BVA-008"; run_and_assert "FR03-BVA-008" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"12345","newPassword":"Test@123"}'; end_tc

OTP=$(get_otp "test@eshop.com")
start_tc "FR03-BVA-009"; run_and_assert "FR03-BVA-009" "200" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$OTP"'","newPassword":"Test@123"}'; end_tc
sqlite3 "$DB" "UPDATE users SET password='$ORIGINAL_HASH' WHERE email='test@eshop.com';"

start_tc "FR03-BVA-010"; run_and_assert "FR03-BVA-010" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"1234567","newPassword":"Test@123"}'; end_tc

VLONG_OTP="$(printf '1%.0s' {1..100})"
start_tc "FR03-BVA-011"; run_and_assert "FR03-BVA-011" "400/401" "POST" "/api/reset-password" "none" '{"email":"test@eshop.com","resetToken":"'"$VLONG_OTP"'","newPassword":"Test@123"}'; end_tc

# Email BVA
P245="$(printf 'a%.0s' {1..245})"
P246="$(printf 'a%.0s' {1..246})"
P247="$(printf 'a%.0s' {1..247})"
P291="$(printf 'a%.0s' {1..291})"

start_tc "FR03-BVA-012"; run_and_assert "FR03-BVA-012" "400/404" "POST" "/api/forgot-password" "none" '{"email":"'"$P245"'@test.com"}'; end_tc
start_tc "FR03-BVA-013"; run_and_assert "FR03-BVA-013" "400/404" "POST" "/api/forgot-password" "none" '{"email":"'"$P246"'@test.com"}'; end_tc
start_tc "FR03-BVA-014"; run_and_assert "FR03-BVA-014" "400" "POST" "/api/forgot-password" "none" '{"email":"'"$P247"'@test.com"}'; end_tc
start_tc "FR03-BVA-015"; run_and_assert "FR03-BVA-015" "400" "POST" "/api/forgot-password" "none" '{"email":"'"$P291"'@test.com"}'; end_tc

# =============================================================================
# FINAL SUMMARY
# =============================================================================
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} FR-03 TEST RESULTS — AUTOMATED CHECKS${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
printf "  %-20s %-20s %-20s %s\n" "TC ID / Check" "Expected" "Actual" "Status"
echo "  ──────────────────────────────────────────────────────────────────"
for row in "${SUMMARY_ROWS[@]}"; do
  IFS='|' read -r S ID EP EXP ACT <<< "$row"
  if [[ "$S" == "PASS" ]]; then C="$GREEN"; else C="$RED"; fi
  printf "  ${C}%-20s %-20s %-20s %s${NC}\n" "${ID:0:20}" "${EXP:0:20}" "${ACT:0:20}" "$S"
done
echo "  ──────────────────────────────────────────────────────────────────"
echo -e "  ${BOLD}TOTAL (automated): ${GREEN}${PASS} PASS${NC} | ${RED}${FAIL} FAIL${NC} | ${YELLOW}${SKIP} SKIP${NC}"
echo ""
echo -e "${YELLOW}  Still requires manual testing:${NC}"
echo -e "    UI-only TCs : FR03-EP-030, FR03-EP-031 → Open app and manually verify."
echo -e "    Mobile UI Validations: Follow checks in scripts/mobile/FR03-ui-manual-checks.md"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Response JSON files saved to: $RESP_DIR/"
echo "Paste the summary block above into Phase B prompt."
