#!/usr/bin/env bash
# =============================================================================
# FR-07: Shopping Cart — API & DB Test Suite
# Generated by: test-execution-assistant skill
# Run from: eshop-sut/ root directory
# Usage:    bash scripts/curl/FR07-api-tests.sh
# Evidence: evidence/api-responses/FR07/
# Requires: curl, python3, sqlite3
# =============================================================================

set -uo pipefail

BASE_URL="http://localhost:3000"
DB="backend/database.sqlite"
RESP_DIR="evidence/api-responses/FR07"
mkdir -p "$RESP_DIR"

# Counters and result accumulator
PASS=0; FAIL=0; SKIP=0
declare -a SUMMARY_ROWS=()

# TC Context Variables
CURRENT_TC_ID=""
CURRENT_TC_FAIL=0
CURRENT_TC_DESC=""
CURRENT_TC_EXP=""
CURRENT_TC_ACT=""

# Color codes
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m';  BOLD='\033[1m';   NC='\033[0m'

# ── Preflight checks ──────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Preflight checks...${NC}"
[[ ! -f "$DB" ]] && echo -e "${RED}ERROR: Database not found at $DB${NC}" && exit 1
curl -sf "$BASE_URL/api/products" > /dev/null \
  || { echo -e "${RED}ERROR: Backend not responding at $BASE_URL${NC}"; exit 1; }
command -v sqlite3 > /dev/null \
  || { echo -e "${RED}ERROR: sqlite3 not installed${NC}"; exit 1; }
echo -e "${GREEN}All systems ready.${NC}\n"

# ── Token Setup ───────────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Acquiring tokens...${NC}"

USER_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"test@eshop.com","password":"Test1234!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

ADMIN_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@eshop.com","password":"Admin123!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

[[ "$USER_TOKEN"  == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get user token${NC}"  && exit 1
[[ "$ADMIN_TOKEN" == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get admin token${NC}" && exit 1
echo -e "${GREEN}Tokens acquired.${NC}\n"

USER_ID=$(sqlite3 "$DB" "SELECT id FROM users WHERE email='test@eshop.com'")
ADMIN_ID=$(sqlite3 "$DB" "SELECT id FROM users WHERE email='admin@eshop.com'")

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

create_test_product() {
  local NAME="$1"
  local PRICE="$2"
  local BODY_FILE="$RESP_DIR/tmp_prod.json"
  python3 -c "
import json, sys
data = {'name': sys.argv[1], 'price': sys.argv[2], 'description': 'test product', 'imageUrl': 'http', 'category_id': 1}
if data['price'] == 'null': data['price'] = None
elif data['price'] != '':
    try: data['price'] = float(data['price']) if '.' in data['price'] else int(data['price'])
    except: pass
with open('$BODY_FILE', 'w') as f: json.dump(data, f)
" "$NAME" "$PRICE"

  local RES
  RES=$(curl -s -X POST "$BASE_URL/api/products" -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" -d "@$BODY_FILE")
  local ID
  ID=$(echo "$RES" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id', '1'))" 2>/dev/null)
  echo "$ID"
}

delete_test_product() {
  local ID="$1"
  echo -e "${YELLOW}[TEARDOWN]${NC} Delete test product $ID via API"
  curl -s -X DELETE "$BASE_URL/api/products/$ID" -H "Authorization: Bearer $ADMIN_TOKEN" >/dev/null
  echo -e "  ${GREEN}Done${NC}"
  echo ""
}

start_tc() {
  CURRENT_TC_ID="$1"
  CURRENT_TC_FAIL=0
  CURRENT_TC_DESC=""
  CURRENT_TC_EXP=""
  CURRENT_TC_ACT=""
}

end_tc() {
  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    ((PASS++))
    SUMMARY_ROWS+=("PASS|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  else
    ((FAIL++))
    SUMMARY_ROWS+=("FAIL|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  fi
}

run_and_assert() {
  local TC_ID="$1" EXPECTED="$2" METHOD="$3" ENDPOINT="$4" TOKEN="$5"
  local BODY_OR_FILE="${6:-}"
  local RESP_FILE="$RESP_DIR/${TC_ID}-response.json"

  local CURL_CMD=(curl -s -o "$RESP_FILE" -w "%{http_code}" -X "$METHOD" "${BASE_URL}${ENDPOINT}" -H "Content-Type: application/json")
  if [[ "$TOKEN" == "user" ]]; then CURL_CMD+=(-H "Authorization: Bearer $USER_TOKEN"); fi
  if [[ "$TOKEN" == "admin" ]]; then CURL_CMD+=(-H "Authorization: Bearer $ADMIN_TOKEN"); fi
  
  if [[ -n "$BODY_OR_FILE" ]]; then 
    if [[ "$BODY_OR_FILE" == @* ]]; then
      CURL_CMD+=(-d "$BODY_OR_FILE")
    else
      CURL_CMD+=(-d "$BODY_OR_FILE")
    fi
  fi

  local ACTUAL
  ACTUAL=$("${CURL_CMD[@]}" 2>/dev/null)

  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  local STATUS COLOR
  if [[ "$ACTUAL" == "$EXPECTED" ]]; then
    STATUS="PASS"; COLOR="$GREEN"
  else
    STATUS="FAIL"; COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${BOLD}${TC_ID}${NC} — HTTP ${ACTUAL} (expected ${EXPECTED})"
  [[ "$STATUS" == "FAIL" ]] && \
    python3 -m json.tool "$RESP_FILE" 2>/dev/null | sed 's/^/        /' || true
  echo ""
}

assert_db() {
  local TC_ID="$1" DESC="$2" SQL="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(sqlite3 "$DB" "$SQL" 2>&1 | tr -d '\n')

  case "$EXPECTED" in
    EXISTS) [[ -n "$ACTUAL" && "$ACTUAL" != Error* ]] && STATUS="PASS" || STATUS="FAIL" ;;
    EMPTY)  [[ -z "$ACTUAL" || "$ACTUAL" == Error* ]] && STATUS="PASS" || STATUS="FAIL" ;;
    BCRYPT) [[ "$ACTUAL" == \$2* ]]                   && STATUS="PASS" || STATUS="FAIL" ;;
    *)      [[ "$ACTUAL" == "$EXPECTED" ]]            && STATUS="PASS" || STATUS="FAIL" ;;
  esac

  if [[ "$STATUS" == "PASS" ]]; then
    COLOR="$GREEN"
  else
    COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="DB: $DESC"
    CURRENT_TC_EXP="$EXPECTED"
    CURRENT_TC_ACT="${ACTUAL:-<empty>}"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — DB: ${DESC}"
  echo -e "       SQL:      ${SQL}"
  echo -e "       Expected: ${EXPECTED} | Actual: ${ACTUAL:-<empty>}"
  echo ""
}

create_payload() {
  local FILE="$1" ID="$2" NAME="$3" PRICE="$4" QTY="$5"
  python3 -c "
import json, sys
data = {'id': sys.argv[1], 'name': sys.argv[2], 'price': sys.argv[3], 'quantity': sys.argv[4]}
for k in ['id', 'price', 'quantity']:
    if data[k] == 'null': data[k] = None
    elif data[k] != '': 
        try: data[k] = float(data[k]) if '.' in data[k] else int(data[k])
        except: pass
with open('$FILE', 'w') as f: json.dump(data, f)
" "$ID" "$NAME" "$PRICE" "$QTY"
}

# =============================================================================
# TEST CASES
# =============================================================================

# ── FR07-EP-001: Happy Path ─────────────────────────────────────────────
echo -e "${CYAN}=== FR07-EP-001: Verify product addition to cart ===${NC}"
start_tc "FR07-EP-001"
PROD_ID=$(create_test_product "Laptop ABC" "100000")
create_payload "$RESP_DIR/EP001.json" "$PROD_ID" "Laptop ABC" "100000" "2"
run_and_assert "FR07-EP-001" "200" "POST" "/api/cart" "user" "@$RESP_DIR/EP001.json"
assert_db "FR07-EP-001-db" "Cart row inserted in DB" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "2"
delete_test_product "$PROD_ID"
end_tc

# ── FR07-EP-002: Merge duplicate product ────────────────────────────────
echo -e "${CYAN}=== FR07-EP-002: Merge duplicate product ===${NC}"
start_tc "FR07-EP-002"
PROD_ID=$(create_test_product "Laptop ABC" "100000")
create_payload "$RESP_DIR/EP002_a.json" "$PROD_ID" "Laptop ABC" "100000" "1"
curl -s -X POST "$BASE_URL/api/cart" -H "Authorization: Bearer $USER_TOKEN" -H "Content-Type: application/json" -d "@$RESP_DIR/EP002_a.json" > /dev/null
create_payload "$RESP_DIR/EP002_b.json" "$PROD_ID" "Laptop ABC" "100000" "2"
run_and_assert "FR07-EP-002" "200" "POST" "/api/cart" "user" "@$RESP_DIR/EP002_b.json"
assert_db "FR07-EP-002-db" "Quantity merged to 3" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "3"
delete_test_product "$PROD_ID"
end_tc

# ── FR07-EP-006: XSS in Name payload ────────────────────────────────────
echo -e "${CYAN}=== FR07-EP-006: XSS in Name payload ===${NC}"
start_tc "FR07-EP-006"
PROD_ID=$(create_test_product "<script>alert(1)</script>" "1000")
create_payload "$RESP_DIR/EP006.json" "$PROD_ID" "<script>alert(1)</script>" "1000" "1"
run_and_assert "FR07-EP-006" "200" "POST" "/api/cart" "user" "@$RESP_DIR/EP006.json"
assert_db "FR07-EP-006-db" "XSS inserted in DB" "SELECT name FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "<script>alert(1)</script>"
delete_test_product "$PROD_ID"
end_tc

# ── FR07-EP-007: Admin Token Auth ───────────────────────────────────────
echo -e "${CYAN}=== FR07-EP-007: Admin Token Auth ===${NC}"
start_tc "FR07-EP-007"
PROD_ID=$(create_test_product "Laptop" "10")
create_payload "$RESP_DIR/EP007.json" "$PROD_ID" "Laptop" "10" "1"
run_and_assert "FR07-EP-007" "200" "POST" "/api/cart" "admin" "@$RESP_DIR/EP007.json"
assert_db "FR07-EP-007-db" "Admin cart inserted" "SELECT quantity FROM cart_items WHERE user_id=$ADMIN_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

# ── FR07-EP-008 to 020: API Rejections ──────────────────────────────────
echo -e "${CYAN}=== FR07-EP-008 to 020: Invalid Parameters ===${NC}"
start_tc "FR07-EP-008"
create_payload "$RESP_DIR/EP008.json" "99999" "Laptop" "100000" "1"
run_and_assert "FR07-EP-008" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP008.json"
end_tc

start_tc "FR07-EP-009"
create_payload "$RESP_DIR/EP009.json" "null" "Laptop" "100000" "1"
run_and_assert "FR07-EP-009" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP009.json"
end_tc

start_tc "FR07-EP-010"
create_payload "$RESP_DIR/EP010.json" "abc" "Laptop" "100000" "1"
run_and_assert "FR07-EP-010" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP010.json"
end_tc

start_tc "FR07-EP-011"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP011.json" "$PROD_ID" "" "100000" "1"
run_and_assert "FR07-EP-011" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP011.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-012"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP012.json" "$PROD_ID" "null" "100000" "1"
run_and_assert "FR07-EP-012" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP012.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-013"
LONG_300=$(printf 'A%.0s' {1..300})
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP013.json" "$PROD_ID" "$LONG_300" "100000" "1"
run_and_assert "FR07-EP-013" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP013.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-014"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP014.json" "$PROD_ID" "Laptop" "0" "1"
run_and_assert "FR07-EP-014" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP014.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-015"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP015.json" "$PROD_ID" "Laptop" "-50000" "1"
run_and_assert "FR07-EP-015" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP015.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-016"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP016.json" "$PROD_ID" "Laptop" "null" "1"
run_and_assert "FR07-EP-016" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP016.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-017"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP017.json" "$PROD_ID" "Laptop" "100000" "0"
run_and_assert "FR07-EP-017" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP017.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-018"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP018.json" "$PROD_ID" "Laptop" "100000" "-1"
run_and_assert "FR07-EP-018" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP018.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-019"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP019.json" "$PROD_ID" "Laptop" "100000" "null"
run_and_assert "FR07-EP-019" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP019.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-020"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/EP020.json" "$PROD_ID" "Laptop" "100000" "1.5"
run_and_assert "FR07-EP-020" "400" "POST" "/api/cart" "user" "@$RESP_DIR/EP020.json"
delete_test_product "$PROD_ID"
end_tc

# ── FR07-EP-021 & 022: Role-Auth Rejections ─────────────────────────────
echo -e "${CYAN}=== FR07-EP-021 & 022: Role-Auth Checks ===${NC}"
start_tc "FR07-EP-021"
PROD_ID=$(create_test_product "Laptop" "100")
create_payload "$RESP_DIR/EP021.json" "$PROD_ID" "Laptop" "100" "1"
run_and_assert "FR07-EP-021" "401" "POST" "/api/cart" "none" "@$RESP_DIR/EP021.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-EP-022"
PROD_ID=$(create_test_product "Laptop" "100")
create_payload "$RESP_DIR/EP022.json" "$PROD_ID" "Laptop" "100" "1"
run_and_assert "FR07-EP-022" "401" "POST" "/api/cart" "none" "@$RESP_DIR/EP022.json" 
delete_test_product "$PROD_ID"
end_tc

# ── BVA TESTS ───────────────────────────────────────────────────────────
echo -e "${CYAN}=== BVA TESTS ===${NC}"

# Quantity BVA
start_tc "FR07-BVA-001"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA001.json" "$PROD_ID" "Laptop" "100000" "null"
run_and_assert "FR07-BVA-001" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA001.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-002"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA002.json" "$PROD_ID" "Laptop" "100000" "0"
run_and_assert "FR07-BVA-002" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA002.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-003"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA003.json" "$PROD_ID" "Laptop" "100000" "1"
run_and_assert "FR07-BVA-003" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA003.json"
assert_db "FR07-BVA-003-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-004"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA004.json" "$PROD_ID" "Laptop" "100000" "2"
run_and_assert "FR07-BVA-004" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA004.json"
assert_db "FR07-BVA-004-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "2"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-005"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA005.json" "$PROD_ID" "Laptop" "100000" "5"
run_and_assert "FR07-BVA-005" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA005.json"
assert_db "FR07-BVA-005-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "5"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-006"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA006.json" "$PROD_ID" "Laptop" "100000" "9999"
run_and_assert "FR07-BVA-006" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA006.json"
assert_db "FR07-BVA-006-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "9999"
delete_test_product "$PROD_ID"
end_tc

# Price BVA
start_tc "FR07-BVA-007"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA007.json" "$PROD_ID" "Laptop" "null" "1"
run_and_assert "FR07-BVA-007" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA007.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-008"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA008.json" "$PROD_ID" "Laptop" "0" "1"
run_and_assert "FR07-BVA-008" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA008.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-009"
PROD_ID=$(create_test_product "Laptop" "1")
create_payload "$RESP_DIR/BVA009.json" "$PROD_ID" "Laptop" "1" "1"
run_and_assert "FR07-BVA-009" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA009.json"
assert_db "FR07-BVA-009-db" "DB Insert" "SELECT price FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-010"
PROD_ID=$(create_test_product "Laptop" "2")
create_payload "$RESP_DIR/BVA010.json" "$PROD_ID" "Laptop" "2" "1"
run_and_assert "FR07-BVA-010" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA010.json"
assert_db "FR07-BVA-010-db" "DB Insert" "SELECT price FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "2"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-011"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA011.json" "$PROD_ID" "Laptop" "100000" "1"
run_and_assert "FR07-BVA-011" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA011.json"
assert_db "FR07-BVA-011-db" "DB Insert" "SELECT price FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "100000"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-012"
PROD_ID=$(create_test_product "Laptop" "2000000000")
create_payload "$RESP_DIR/BVA012.json" "$PROD_ID" "Laptop" "2000000000" "1"
run_and_assert "FR07-BVA-012" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA012.json"
assert_db "FR07-BVA-012-db" "DB Insert" "SELECT price FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "2000000000"
delete_test_product "$PROD_ID"
end_tc

# Name Length BVA
start_tc "FR07-BVA-013"
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA013.json" "$PROD_ID" "" "100000" "1"
run_and_assert "FR07-BVA-013" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA013.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-014"
LONG_1=$(printf 'A%.0s' {1..1})
PROD_ID=$(create_test_product "$LONG_1" "100000")
create_payload "$RESP_DIR/BVA014.json" "$PROD_ID" "$LONG_1" "100000" "1"
run_and_assert "FR07-BVA-014" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA014.json"
assert_db "FR07-BVA-014-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-015"
LONG_2=$(printf 'A%.0s' {1..2})
PROD_ID=$(create_test_product "$LONG_2" "100000")
create_payload "$RESP_DIR/BVA015.json" "$PROD_ID" "$LONG_2" "100000" "1"
run_and_assert "FR07-BVA-015" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA015.json"
assert_db "FR07-BVA-015-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-016"
LONG_6=$(printf 'A%.0s' {1..6})
PROD_ID=$(create_test_product "$LONG_6" "100000")
create_payload "$RESP_DIR/BVA016.json" "$PROD_ID" "$LONG_6" "100000" "1"
run_and_assert "FR07-BVA-016" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA016.json"
assert_db "FR07-BVA-016-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-017"
LONG_254=$(printf 'A%.0s' {1..254})
PROD_ID=$(create_test_product "$LONG_254" "100000")
create_payload "$RESP_DIR/BVA017.json" "$PROD_ID" "$LONG_254" "100000" "1"
run_and_assert "FR07-BVA-017" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA017.json"
assert_db "FR07-BVA-017-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-018"
LONG_255=$(printf 'A%.0s' {1..255})
PROD_ID=$(create_test_product "$LONG_255" "100000")
create_payload "$RESP_DIR/BVA018.json" "$PROD_ID" "$LONG_255" "100000" "1"
run_and_assert "FR07-BVA-018" "200" "POST" "/api/cart" "user" "@$RESP_DIR/BVA018.json"
assert_db "FR07-BVA-018-db" "DB Insert" "SELECT quantity FROM cart_items WHERE user_id=$USER_ID AND product_id=$PROD_ID;" "1"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-019"
LONG_256=$(printf 'A%.0s' {1..256})
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA019.json" "$PROD_ID" "$LONG_256" "100000" "1"
run_and_assert "FR07-BVA-019" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA019.json"
delete_test_product "$PROD_ID"
end_tc

start_tc "FR07-BVA-020"
LONG_1000=$(printf 'A%.0s' {1..1000})
PROD_ID=$(create_test_product "Laptop" "100000")
create_payload "$RESP_DIR/BVA020.json" "$PROD_ID" "$LONG_1000" "100000" "1"
run_and_assert "FR07-BVA-020" "400" "POST" "/api/cart" "user" "@$RESP_DIR/BVA020.json"
delete_test_product "$PROD_ID"
end_tc

# =============================================================================
# FINAL SUMMARY
# =============================================================================

echo -e "${YELLOW}>>> Cleaning up temporary payload files...${NC}"
find "$RESP_DIR" -type f ! -name "*-response.json" -delete
echo -e "  ${GREEN}Done. Only API responses are kept.${NC}"

echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} FR-07 TEST RESULTS — AUTOMATED CHECKS${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
printf "  %-20s %-30s %-45s %s\n" "TC ID / Check" "Expected" "Actual" "Status"
echo "  ──────────────────────────────────────────────────────────────────"
for row in "${SUMMARY_ROWS[@]}"; do
  IFS='|' read -r S ID EP EXP ACT <<< "$row"
  [[ "$S" == "PASS" ]] && C="$GREEN" || C="$RED"
  printf "  ${C}%-20s %-30s %-45s %s${NC}\n" \
    "${ID:0:20}" "${EXP:0:30}" "${ACT:0:45}" "$S"
done
echo "  ──────────────────────────────────────────────────────────────────"
echo -e "  ${BOLD}TOTAL (automated): ${GREEN}${PASS} PASS${NC} | ${RED}${FAIL} FAIL${NC} | ${YELLOW}${SKIP} SKIP${NC}"
echo ""
echo -e "${YELLOW}  Still requires manual testing:${NC}"
echo -e "    UI-only TCs : FR07-EP-003 → open http://localhost:5173"
echo -e "    DOM checks  : paste scripts/curl/FR07-dom-checks.js into DevTools"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Response JSON files saved to: $RESP_DIR/"
echo "Paste the summary block above into Phase B prompt."
