#!/usr/bin/env bash
# =============================================================================
# FR-17: Coupon Management (Admin CRUD) — API & DB Test Suite
# Generated by: test-execution-assistant skill
# Run from:     eshop-sut/ root directory
# Usage:        bash scripts/curl/FR17-api-tests.sh
# Evidence:     evidence/api-responses/FR17/
# Requires:     curl, python3, sqlite3
# =============================================================================

set -uo pipefail

BASE_URL="http://localhost:3000"
DB="backend/database.sqlite"
RESP_DIR="evidence/api-responses/FR17"
mkdir -p "$RESP_DIR"

PASS=0; FAIL=0; SKIP=0
declare -a SUMMARY_ROWS=()

CURRENT_TC_ID=""
CURRENT_TC_FAIL=0
CURRENT_TC_DESC=""
CURRENT_TC_EXP=""
CURRENT_TC_ACT=""

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m';  BOLD='\033[1m';   NC='\033[0m'

# ── Dynamic date variables ────────────────────────────────────────────────────
TODAY=$(date +%Y-%m-%d)
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)
TOMORROW=$(date -d "tomorrow"  +%Y-%m-%d 2>/dev/null || date -v+1d +%Y-%m-%d)

# ── Preflight checks ──────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Preflight checks...${NC}"
[[ ! -f "$DB" ]] && echo -e "${RED}ERROR: Database not found at $DB${NC}" && exit 1
curl -sf "$BASE_URL/api/products" > /dev/null \
  || { echo -e "${RED}ERROR: Backend not responding at $BASE_URL${NC}"; exit 1; }
command -v sqlite3 > /dev/null \
  || { echo -e "${RED}ERROR: sqlite3 not installed${NC}"; exit 1; }
echo -e "${GREEN}All systems ready.${NC}\n"
echo "  Dynamic dates: TODAY=$TODAY | YESTERDAY=$YESTERDAY | TOMORROW=$TOMORROW"
echo ""

# ── Token Setup ───────────────────────────────────────────────────────────────
echo -e "${BOLD}>>> Acquiring tokens...${NC}"

USER_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"test@eshop.com","password":"Test1234!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

ADMIN_TOKEN=$(curl -s -X POST "$BASE_URL/api/login" \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@eshop.com","password":"Admin123!"}' \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token','TOKEN_ERROR'))" 2>/dev/null)

[[ "$USER_TOKEN"  == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get user token${NC}"  && exit 1
[[ "$ADMIN_TOKEN" == "TOKEN_ERROR" ]] && echo -e "${RED}ERROR: Cannot get admin token${NC}" && exit 1
echo -e "${GREEN}Tokens acquired.${NC}\n"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

start_tc() {
  CURRENT_TC_ID="$1"
  CURRENT_TC_FAIL=0
  CURRENT_TC_DESC=""
  CURRENT_TC_EXP=""
  CURRENT_TC_ACT=""
}

end_tc() {
  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    ((PASS++))
    SUMMARY_ROWS+=("PASS|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  else
    ((FAIL++))
    SUMMARY_ROWS+=("FAIL|$CURRENT_TC_ID|$CURRENT_TC_DESC|$CURRENT_TC_EXP|$CURRENT_TC_ACT")
  fi
}

run_and_assert() {
  local TC_ID="$1" EXPECTED="$2" METHOD="$3" ENDPOINT="$4" TOKEN="$5"
  local BODY="${6:-}"
  local RESP_FILE="$RESP_DIR/${TC_ID}-response.json"

  local -a CURL_CMD=(curl -s -o "$RESP_FILE" -w "%{http_code}"
    -X "$METHOD" "${BASE_URL}${ENDPOINT}"
    -H "Content-Type: application/json")
  [[ "$TOKEN" == "user"  ]] && CURL_CMD+=(-H "Authorization: Bearer $USER_TOKEN")
  [[ "$TOKEN" == "admin" ]] && CURL_CMD+=(-H "Authorization: Bearer $ADMIN_TOKEN")
  [[ "$TOKEN" == "invalid" ]] && CURL_CMD+=(-H "Authorization: Bearer invalidtoken123")
  [[ -n "$BODY" ]] && CURL_CMD+=(-d "$BODY")

  local ACTUAL
  ACTUAL=$("${CURL_CMD[@]}" 2>/dev/null)

  if [[ $CURRENT_TC_FAIL -eq 0 ]]; then
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  local STATUS COLOR
  if [[ "$ACTUAL" == "$EXPECTED" ]]; then
    STATUS="PASS"; COLOR="$GREEN"
  else
    STATUS="FAIL"; COLOR="$RED"
    CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="$METHOD $ENDPOINT"
    CURRENT_TC_EXP="HTTP $EXPECTED"
    CURRENT_TC_ACT="HTTP $ACTUAL"
  fi

  echo -e "${COLOR}[${STATUS}]${NC} ${BOLD}${TC_ID}${NC} — HTTP ${ACTUAL} (expected ${EXPECTED})"
  [[ "$STATUS" == "FAIL" ]] && \
    python3 -m json.tool "$RESP_FILE" 2>/dev/null | sed 's/^/        /' || true
  echo ""
}

assert_json_field() {
  local TC_ID="$1" RESP_FILE="$2" FIELD="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(python3 -c "
import json, sys
try:
    d = json.load(open('$RESP_FILE'))
    v = d.get('$FIELD', '__MISSING__')
    print(str(v))
except Exception as e:
    print('__ERROR__:' + str(e))
" 2>/dev/null)

  if   [[ "$EXPECTED" == "EXISTS"       && "$ACTUAL" != "__MISSING__" && "$ACTUAL" != __ERROR__* ]]; then STATUS="PASS"
  elif [[ "$EXPECTED" == "POSITIVE_INT" ]] && python3 -c "v=int('$ACTUAL'); exit(0 if v>0 else 1)" 2>/dev/null; then STATUS="PASS"
  elif [[ "$EXPECTED" != "EXISTS" && "$EXPECTED" != "POSITIVE_INT" && "$ACTUAL" == "$EXPECTED" ]]; then STATUS="PASS"
  else STATUS="FAIL"
  fi

  [[ "$STATUS" == "PASS" ]] && COLOR="$GREEN" || { COLOR="$RED"; CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="json[$FIELD]"; CURRENT_TC_EXP="$EXPECTED"; CURRENT_TC_ACT="${ACTUAL:0:40}"; }

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — json['${FIELD}']: expected=${EXPECTED}, actual=${ACTUAL}"
}

assert_db() {
  local TC_ID="$1" DESC="$2" SQL="$3" EXPECTED="$4"
  local ACTUAL STATUS COLOR

  ACTUAL=$(sqlite3 "$DB" "$SQL" 2>/dev/null)

  case "$EXPECTED" in
    EXISTS) [[ -n "$ACTUAL" ]]              && STATUS="PASS" || STATUS="FAIL" ;;
    EMPTY)  [[ -z "$ACTUAL" ]]              && STATUS="PASS" || STATUS="FAIL" ;;
    BCRYPT) [[ "$ACTUAL" == \$2* ]]         && STATUS="PASS" || STATUS="FAIL" ;;
    *)      [[ "$ACTUAL" == "$EXPECTED" ]]  && STATUS="PASS" || STATUS="FAIL" ;;
  esac

  [[ "$STATUS" == "PASS" ]] && COLOR="$GREEN" || { COLOR="$RED"; CURRENT_TC_FAIL=1
    CURRENT_TC_DESC="DB: $DESC"; CURRENT_TC_EXP="$EXPECTED"; CURRENT_TC_ACT="${ACTUAL:-<empty>}"; }

  echo -e "${COLOR}[${STATUS}]${NC} ${TC_ID} — DB: ${DESC}"
  echo -e "       SQL:      ${SQL}"
  echo -e "       Expected: ${EXPECTED} | Actual: ${ACTUAL:-<empty>}"
  echo ""
}

teardown_db() {
  local DESC="$1" SQL="$2"
  echo -e "${YELLOW}[TEARDOWN]${NC} $DESC"
  sqlite3 "$DB" "$SQL" 2>/dev/null \
    && echo -e "  ${GREEN}Done${NC}" \
    || echo -e "  ${YELLOW}Nothing to delete (OK if TC was expected to fail)${NC}"
  echo ""
}

# Helper: extract coupon ID from DB after creation, then teardown by ID
teardown_coupon_by_code() {
  local CODE="$1"
  local ID
  ID=$(sqlite3 "$DB" "SELECT id FROM coupons WHERE code='${CODE}';" 2>/dev/null)
  if [[ -n "$ID" ]]; then
    teardown_db "Delete coupon code=${CODE} (id=${ID})" \
      "DELETE FROM coupons WHERE code='${CODE}';"
  else
    echo -e "${YELLOW}[TEARDOWN]${NC} code=${CODE} not found in DB (expected if TC failed)."
    echo ""
  fi
}

# =============================================================================
# ── PART 1: EP TEST CASES ─────────────────────────────────────────────────────
# =============================================================================

# ── FR17-EP-001: Happy Path — all valid inputs ────────────────────────────────
# EC Ref: EC01, EC06, EC12, EC19, EC25, EC28, EC38 | Expected: 200
echo -e "${CYAN}=== FR17-EP-001: Happy Path — all valid inputs ===${NC}"
start_tc "FR17-EP-001"

run_and_assert "FR17-EP-001" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"SUMMER25","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":200000,"max_uses_per_user":1}'

assert_json_field "FR17-EP-001-res-id" "$RESP_DIR/FR17-EP-001-response.json" "id" "POSITIVE_INT"

assert_db "FR17-EP-001-db" "Coupon SUMMER25 exists in coupons table" \
  "SELECT code FROM coupons WHERE code='SUMMER25';" "SUMMER25"

teardown_coupon_by_code "SUMMER25"
end_tc

# ── FR17-EP-002: Happy Path — fixed type, zero min_order_amount ──────────────
# EC Ref: EC01, EC07, EC12, EC19, EC24, EC29, EC38 | Expected: 200
echo -e "${CYAN}=== FR17-EP-002: Happy Path — fixed type, zero min_order_amount ===${NC}"
start_tc "FR17-EP-002"

run_and_assert "FR17-EP-002" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BIGDEAL01","type":"fixed","discount_value":50000,"expired_at":"2099-12-31","min_order_amount":0,"max_uses_per_user":3}'

assert_json_field "FR17-EP-002-res-id" "$RESP_DIR/FR17-EP-002-response.json" "id" "POSITIVE_INT"

assert_db "FR17-EP-002-db" "Coupon BIGDEAL01 exists with type=fixed" \
  "SELECT type FROM coupons WHERE code='BIGDEAL01';" "fixed"

teardown_coupon_by_code "BIGDEAL01"
end_tc

# ── FR17-EP-003: Happy Path — XSS input (MANUAL — UI only) ───────────────────
echo -e "${YELLOW}[MANUAL]${NC} FR17-EP-003 — XSS check requires Admin UI. Skipping script."
((SKIP++))
SUMMARY_ROWS+=("SKIP|FR17-EP-003|UI manual|N/A|Human only")
echo ""

# ── FR17-EP-004: Happy Path — Delete existing coupon ─────────────────────────
# EC Ref: EC34, EC38 | Expected: 200
echo -e "${CYAN}=== FR17-EP-004: Happy Path — Delete existing coupon ===${NC}"
start_tc "FR17-EP-004"

# Insert a coupon to delete
sqlite3 "$DB" "INSERT INTO coupons (code, type, discount_value, min_order_amount, expired_at, max_uses_per_user, is_active) \
  VALUES ('DELTEST01','percent',10,100000,'2099-12-31',1,1);" 2>/dev/null
DEL_ID=$(sqlite3 "$DB" "SELECT id FROM coupons WHERE code='DELTEST01';")

run_and_assert "FR17-EP-004" "200" "DELETE" "/api/admin/coupons/${DEL_ID}" "admin"

assert_db "FR17-EP-004-db" "Coupon DELTEST01 removed from DB" \
  "SELECT COUNT(*) FROM coupons WHERE code='DELTEST01';" "0"

# Safety teardown in case DELETE failed
teardown_coupon_by_code "DELTEST01"
end_tc

# ── FR17-EP-005: Happy Path — List coupons ───────────────────────────────────
# EC Ref: EC38 | Expected: 200
echo -e "${CYAN}=== FR17-EP-005: Happy Path — List coupons with admin JWT ===${NC}"
start_tc "FR17-EP-005"

run_and_assert "FR17-EP-005" "200" "GET" "/api/coupons" "admin"
end_tc

# ── FR17-EP-006: DOM checks (DOM channel — handled by JS script) ──────────────
echo -e "${YELLOW}[DOM]${NC} FR17-EP-006 — Navigate to http://localhost:5174 and run FR17-dom-checks.js"
((SKIP++))
SUMMARY_ROWS+=("SKIP|FR17-EP-006|DOM JS script|N/A|Run FR17-dom-checks.js")
echo ""

# ── FR17-EP-007: Invalid code — empty string ─────────────────────────────────
# EC Ref: EC03 | Expected: 400
echo -e "${CYAN}=== FR17-EP-007: Invalid code — empty string ===${NC}"
start_tc "FR17-EP-007"
run_and_assert "FR17-EP-007" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-008: Invalid code — missing field ─────────────────────────────────
# EC Ref: EC04 | Expected: 400
echo -e "${CYAN}=== FR17-EP-008: Invalid code — missing field ===${NC}"
start_tc "FR17-EP-008"
run_and_assert "FR17-EP-008" "400" "POST" "/api/admin/coupons" "admin" \
  '{"type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-009: Invalid code — duplicate (SAVE10 exists in seed) ─────────────
# EC Ref: EC05 | Expected: 400
echo -e "${CYAN}=== FR17-EP-009: Invalid code — duplicate (SAVE10 already in DB) ===${NC}"
start_tc "FR17-EP-009"
run_and_assert "FR17-EP-009" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"SAVE10","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-010: Invalid type — unknown enum value ────────────────────────────
# EC Ref: EC08 | Expected: 400
echo -e "${CYAN}=== FR17-EP-010: Invalid type — unknown enum 'discount' ===${NC}"
start_tc "FR17-EP-010"
run_and_assert "FR17-EP-010" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"discount","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-011: Invalid type — uppercase enum value ─────────────────────────
# EC Ref: EC09 | Expected: 400
echo -e "${CYAN}=== FR17-EP-011: Invalid type — uppercase 'PERCENT' ===${NC}"
start_tc "FR17-EP-011"
run_and_assert "FR17-EP-011" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"PERCENT","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-012: Invalid type — empty string ─────────────────────────────────
# EC Ref: EC10 | Expected: 400
echo -e "${CYAN}=== FR17-EP-012: Invalid type — empty string ===${NC}"
start_tc "FR17-EP-012"
run_and_assert "FR17-EP-012" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-013: Invalid type — missing field ─────────────────────────────────
# EC Ref: EC11 | Expected: 400
echo -e "${CYAN}=== FR17-EP-013: Invalid type — missing field ===${NC}"
start_tc "FR17-EP-013"
run_and_assert "FR17-EP-013" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-014: Invalid discount_value — exactly zero ───────────────────────
# EC Ref: EC13 | Expected: 400
echo -e "${CYAN}=== FR17-EP-014: Invalid discount_value — exactly 0 ===${NC}"
start_tc "FR17-EP-014"
run_and_assert "FR17-EP-014" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":0,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-015: Invalid discount_value — negative ───────────────────────────
# EC Ref: EC14 | Expected: 400
echo -e "${CYAN}=== FR17-EP-015: Invalid discount_value — negative (-10) ===${NC}"
start_tc "FR17-EP-015"
run_and_assert "FR17-EP-015" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":-10,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-016: Invalid discount_value — missing field ──────────────────────
# EC Ref: EC15 | Expected: 400
echo -e "${CYAN}=== FR17-EP-016: Invalid discount_value — missing field ===${NC}"
start_tc "FR17-EP-016"
run_and_assert "FR17-EP-016" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-017: Invalid discount_value — non-numeric string ─────────────────
# EC Ref: EC16 | Expected: 400
echo -e "${CYAN}=== FR17-EP-017: Invalid discount_value — non-numeric 'abc' ===${NC}"
start_tc "FR17-EP-017"
run_and_assert "FR17-EP-017" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":"abc","expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-018: Invalid discount_value — percent > 100 ──────────────────────
# EC Ref: EC18 | Expected: 400 (flag if 200 — no upper-limit enforcement)
echo -e "${CYAN}=== FR17-EP-018: Invalid discount_value — percent=101 exceeds 100% ===${NC}"
start_tc "FR17-EP-018"
run_and_assert "FR17-EP-018" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":101,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "NEWCODE01"
end_tc

# ── FR17-EP-019: Invalid expired_at — past date ───────────────────────────────
# EC Ref: EC20 | Expected: 400 (BR-05)
echo -e "${CYAN}=== FR17-EP-019: Invalid expired_at — past date 2020-01-01 ===${NC}"
start_tc "FR17-EP-019"
run_and_assert "FR17-EP-019" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2020-01-01","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-020: Invalid expired_at — wrong format DD-MM-YYYY ────────────────
# EC Ref: EC21 | Expected: 400
echo -e "${CYAN}=== FR17-EP-020: Invalid expired_at — wrong format '31-12-2099' ===${NC}"
start_tc "FR17-EP-020"
run_and_assert "FR17-EP-020" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"31-12-2099","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-021: Invalid expired_at — non-date string ─────────────────────────
# EC Ref: EC22 | Expected: 400
echo -e "${CYAN}=== FR17-EP-021: Invalid expired_at — non-date string 'notadate' ===${NC}"
start_tc "FR17-EP-021"
run_and_assert "FR17-EP-021" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"notadate","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-022: Invalid expired_at — missing field ──────────────────────────
# EC Ref: EC23 | Expected: 400
echo -e "${CYAN}=== FR17-EP-022: Invalid expired_at — missing field ===${NC}"
start_tc "FR17-EP-022"
run_and_assert "FR17-EP-022" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"min_order_amount":100000,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-023: Invalid min_order_amount — negative ─────────────────────────
# EC Ref: EC26 | Expected: 400
echo -e "${CYAN}=== FR17-EP-023: Invalid min_order_amount — negative (-1) ===${NC}"
start_tc "FR17-EP-023"
run_and_assert "FR17-EP-023" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":-1,"max_uses_per_user":1}'
end_tc

# ── FR17-EP-024: Invalid min_order_amount — missing field ────────────────────
# EC Ref: EC27 | Expected: 400
echo -e "${CYAN}=== FR17-EP-024: Invalid min_order_amount — missing field ===${NC}"
start_tc "FR17-EP-024"
run_and_assert "FR17-EP-024" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","max_uses_per_user":1}'
end_tc

# ── FR17-EP-025: Invalid max_uses_per_user — exactly zero ────────────────────
# EC Ref: EC30 | Expected: 400
echo -e "${CYAN}=== FR17-EP-025: Invalid max_uses_per_user — exactly 0 ===${NC}"
start_tc "FR17-EP-025"
run_and_assert "FR17-EP-025" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":0}'
end_tc

# ── FR17-EP-026: Invalid max_uses_per_user — negative ────────────────────────
# EC Ref: EC31 | Expected: 400
echo -e "${CYAN}=== FR17-EP-026: Invalid max_uses_per_user — negative (-1) ===${NC}"
start_tc "FR17-EP-026"
run_and_assert "FR17-EP-026" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":-1}'
end_tc

# ── FR17-EP-027: Invalid max_uses_per_user — missing field ───────────────────
# EC Ref: EC32 | Expected: 400
echo -e "${CYAN}=== FR17-EP-027: Invalid max_uses_per_user — missing field ===${NC}"
start_tc "FR17-EP-027"
run_and_assert "FR17-EP-027" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000}'
end_tc

# ── FR17-EP-028: Invalid max_uses_per_user — float value ─────────────────────
# EC Ref: EC33 | Expected: 400
echo -e "${CYAN}=== FR17-EP-028: Invalid max_uses_per_user — float (1.5) ===${NC}"
start_tc "FR17-EP-028"
run_and_assert "FR17-EP-028" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"NEWCODE01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1.5}'
end_tc

# ── FR17-EP-029: Invalid DELETE — non-existent ID ────────────────────────────
# EC Ref: EC35 | Expected: 404
echo -e "${CYAN}=== FR17-EP-029: Invalid DELETE — non-existent ID 99999 ===${NC}"
start_tc "FR17-EP-029"
run_and_assert "FR17-EP-029" "404" "DELETE" "/api/admin/coupons/99999" "admin"
end_tc

# ── FR17-EP-030: Invalid DELETE — non-numeric ID ─────────────────────────────
# EC Ref: EC36 | Expected: 400 or 404
echo -e "${CYAN}=== FR17-EP-030: Invalid DELETE — non-numeric ID 'abc' ===${NC}"
start_tc "FR17-EP-030"
# Accept either 400 or 404 — both are valid error responses
HTTP_030=$(curl -s -o "$RESP_DIR/FR17-EP-030-response.json" \
  -w "%{http_code}" -X DELETE "${BASE_URL}/api/admin/coupons/abc" \
  -H "Authorization: Bearer $ADMIN_TOKEN" 2>/dev/null)
CURRENT_TC_DESC="DELETE /api/admin/coupons/abc"
CURRENT_TC_EXP="HTTP 400 or 404"
CURRENT_TC_ACT="HTTP $HTTP_030"
if [[ "$HTTP_030" == "400" || "$HTTP_030" == "404" ]]; then
  echo -e "${GREEN}[PASS]${NC} FR17-EP-030 — HTTP ${HTTP_030} (expected 400 or 404)"
else
  echo -e "${RED}[FAIL]${NC} FR17-EP-030 — HTTP ${HTTP_030} (expected 400 or 404)"
  CURRENT_TC_FAIL=1
fi
echo ""
end_tc

# ── FR17-EP-031: Invalid DELETE — zero ID ────────────────────────────────────
# EC Ref: EC37 | Expected: 400 or 404
echo -e "${CYAN}=== FR17-EP-031: Invalid DELETE — zero ID ===${NC}"
start_tc "FR17-EP-031"
HTTP_031=$(curl -s -o "$RESP_DIR/FR17-EP-031-response.json" \
  -w "%{http_code}" -X DELETE "${BASE_URL}/api/admin/coupons/0" \
  -H "Authorization: Bearer $ADMIN_TOKEN" 2>/dev/null)
CURRENT_TC_DESC="DELETE /api/admin/coupons/0"
CURRENT_TC_EXP="HTTP 400 or 404"
CURRENT_TC_ACT="HTTP $HTTP_031"
if [[ "$HTTP_031" == "400" || "$HTTP_031" == "404" ]]; then
  echo -e "${GREEN}[PASS]${NC} FR17-EP-031 — HTTP ${HTTP_031} (expected 400 or 404)"
else
  echo -e "${RED}[FAIL]${NC} FR17-EP-031 — HTTP ${HTTP_031} (expected 400 or 404)"
  CURRENT_TC_FAIL=1
fi
echo ""
end_tc

# ── FR17-EP-032 / 033 / 034: Role-Auth — POST /api/admin/coupons ─────────────
# Pattern C: no-token→401, user-token→403, invalid-token→401, admin→200
RA_POST_BODY='{"code":"RATEST01","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'

echo -e "${CYAN}=== FR17-EP-032: Role-Auth — POST without token ===${NC}"
start_tc "FR17-EP-032"
run_and_assert "FR17-EP-032" "401" "POST" "/api/admin/coupons" "none" "$RA_POST_BODY"
end_tc

echo -e "${CYAN}=== FR17-EP-033: Role-Auth — POST with user token (non-admin) ===${NC}"
start_tc "FR17-EP-033"
run_and_assert "FR17-EP-033" "403" "POST" "/api/admin/coupons" "user" "$RA_POST_BODY"
end_tc

echo -e "${CYAN}=== FR17-EP-034: Role-Auth — POST with malformed/invalid token ===${NC}"
start_tc "FR17-EP-034"
run_and_assert "FR17-EP-034" "401" "POST" "/api/admin/coupons" "invalid" "$RA_POST_BODY"
end_tc

# Verify admin POST still works (confirm Role-Auth baseline is correct)
# Use a dedicated code so we can teardown safely
RA_ADMIN_BODY='{"code":"RATEST02","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
curl -s -o /dev/null -X POST "${BASE_URL}/api/admin/coupons" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ADMIN_TOKEN" \
  -d "$RA_ADMIN_BODY" 2>/dev/null
teardown_coupon_by_code "RATEST01"
teardown_coupon_by_code "RATEST02"

# ── FR17-EP-035 / 036: Role-Auth — DELETE /api/admin/coupons/:id ─────────────
# Pre-insert a coupon to target for DELETE Role-Auth tests
sqlite3 "$DB" "INSERT OR IGNORE INTO coupons (code,type,discount_value,min_order_amount,expired_at,max_uses_per_user,is_active) \
  VALUES ('RADEL01','percent',10,100000,'2099-12-31',1,1);" 2>/dev/null
RADEL_ID=$(sqlite3 "$DB" "SELECT id FROM coupons WHERE code='RADEL01';")

echo -e "${CYAN}=== FR17-EP-035: Role-Auth — DELETE without token ===${NC}"
start_tc "FR17-EP-035"
run_and_assert "FR17-EP-035" "401" "DELETE" "/api/admin/coupons/${RADEL_ID}" "none"
end_tc

echo -e "${CYAN}=== FR17-EP-036: Role-Auth — DELETE with user token ===${NC}"
start_tc "FR17-EP-036"
run_and_assert "FR17-EP-036" "403" "DELETE" "/api/admin/coupons/${RADEL_ID}" "user"
end_tc

teardown_coupon_by_code "RADEL01"

# ── FR17-EP-037 / 038: Role-Auth — GET /api/coupons ─────────────────────────
echo -e "${CYAN}=== FR17-EP-037: Role-Auth — GET /api/coupons without token ===${NC}"
start_tc "FR17-EP-037"
run_and_assert "FR17-EP-037" "401" "GET" "/api/coupons" "none"
end_tc

echo -e "${CYAN}=== FR17-EP-038: Role-Auth — GET /api/coupons with user token ===${NC}"
start_tc "FR17-EP-038"
run_and_assert "FR17-EP-038" "403" "GET" "/api/coupons" "user"
end_tc

# =============================================================================
# ── PART 2: BVA TEST CASES ────────────────────────────────────────────────────
# =============================================================================

# ─── BVA: discount_value ─────────────────────────────────────────────────────

echo -e "${CYAN}=== FR17-BVA-001: discount_value -α — omitted/empty ===${NC}"
start_tc "FR17-BVA-001"
run_and_assert "FR17-BVA-001" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA01","type":"percent","expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-002: discount_value LB-1 — exactly 0 ===${NC}"
start_tc "FR17-BVA-002"
run_and_assert "FR17-BVA-002" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA02","type":"percent","discount_value":0,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-003: discount_value LB — exactly 1 (valid) ===${NC}"
start_tc "FR17-BVA-003"
run_and_assert "FR17-BVA-003" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA03","type":"percent","discount_value":1,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA03"
end_tc

echo -e "${CYAN}=== FR17-BVA-004: discount_value LB+1 — exactly 2 (valid) ===${NC}"
start_tc "FR17-BVA-004"
run_and_assert "FR17-BVA-004" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA04","type":"percent","discount_value":2,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA04"
end_tc

echo -e "${CYAN}=== FR17-BVA-005: discount_value Nominal — 50% (valid) ===${NC}"
start_tc "FR17-BVA-005"
run_and_assert "FR17-BVA-005" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA05","type":"percent","discount_value":50,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA05"
end_tc

echo -e "${CYAN}=== FR17-BVA-006: discount_value UB-1 — 99% (valid) ===${NC}"
start_tc "FR17-BVA-006"
run_and_assert "FR17-BVA-006" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA06","type":"percent","discount_value":99,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA06"
end_tc

echo -e "${CYAN}=== FR17-BVA-007: discount_value UB — 100% (valid) ===${NC}"
start_tc "FR17-BVA-007"
run_and_assert "FR17-BVA-007" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA07","type":"percent","discount_value":100,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA07"
end_tc

echo -e "${CYAN}=== FR17-BVA-008: discount_value UB+1 — 101% (flag if accepted) ===${NC}"
start_tc "FR17-BVA-008"
run_and_assert "FR17-BVA-008" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA08","type":"percent","discount_value":101,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA08"
end_tc

echo -e "${CYAN}=== FR17-BVA-009: discount_value +α — 9999999 (very large) ===${NC}"
start_tc "FR17-BVA-009"
run_and_assert "FR17-BVA-009" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA09","type":"percent","discount_value":9999999,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA09"
end_tc

# ─── BVA: min_order_amount ───────────────────────────────────────────────────

echo -e "${CYAN}=== FR17-BVA-010: min_order_amount -α — omitted ===${NC}"
start_tc "FR17-BVA-010"
run_and_assert "FR17-BVA-010" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA10","type":"percent","discount_value":15,"expired_at":"2099-12-31","max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-011: min_order_amount LB-1 — exactly -1 ===${NC}"
start_tc "FR17-BVA-011"
run_and_assert "FR17-BVA-011" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA11","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":-1,"max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-012: min_order_amount LB — exactly 0 (valid) ===${NC}"
start_tc "FR17-BVA-012"
run_and_assert "FR17-BVA-012" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA12","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":0,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA12"
end_tc

echo -e "${CYAN}=== FR17-BVA-013: min_order_amount LB+1 — exactly 1 (valid) ===${NC}"
start_tc "FR17-BVA-013"
run_and_assert "FR17-BVA-013" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA13","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":1,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA13"
end_tc

echo -e "${CYAN}=== FR17-BVA-014: min_order_amount Nominal — 500000 (valid) ===${NC}"
start_tc "FR17-BVA-014"
run_and_assert "FR17-BVA-014" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA14","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":500000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA14"
end_tc

echo -e "${CYAN}=== FR17-BVA-015: min_order_amount +α — 999999999 (valid/DB limit) ===${NC}"
start_tc "FR17-BVA-015"
run_and_assert "FR17-BVA-015" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA15","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":999999999,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA15"
end_tc

# ─── BVA: max_uses_per_user ──────────────────────────────────────────────────

echo -e "${CYAN}=== FR17-BVA-016: max_uses_per_user -α — omitted ===${NC}"
start_tc "FR17-BVA-016"
run_and_assert "FR17-BVA-016" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA16","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000}'
end_tc

echo -e "${CYAN}=== FR17-BVA-017: max_uses_per_user LB-1 — exactly 0 ===${NC}"
start_tc "FR17-BVA-017"
run_and_assert "FR17-BVA-017" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA17","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":0}'
end_tc

echo -e "${CYAN}=== FR17-BVA-018: max_uses_per_user LB — exactly 1 (valid) ===${NC}"
start_tc "FR17-BVA-018"
run_and_assert "FR17-BVA-018" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA18","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA18"
end_tc

echo -e "${CYAN}=== FR17-BVA-019: max_uses_per_user LB+1 — exactly 2 (valid) ===${NC}"
start_tc "FR17-BVA-019"
run_and_assert "FR17-BVA-019" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA19","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":2}'
teardown_coupon_by_code "BVA19"
end_tc

echo -e "${CYAN}=== FR17-BVA-020: max_uses_per_user Nominal — 10 (valid) ===${NC}"
start_tc "FR17-BVA-020"
run_and_assert "FR17-BVA-020" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA20","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":10}'
teardown_coupon_by_code "BVA20"
end_tc

echo -e "${CYAN}=== FR17-BVA-021: max_uses_per_user +α — 9999 (valid/DB limit) ===${NC}"
start_tc "FR17-BVA-021"
run_and_assert "FR17-BVA-021" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA21","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":9999}'
teardown_coupon_by_code "BVA21"
end_tc

# ─── BVA: expired_at (dynamic dates) ─────────────────────────────────────────

echo -e "${CYAN}=== FR17-BVA-022: expired_at -α — omitted ===${NC}"
start_tc "FR17-BVA-022"
run_and_assert "FR17-BVA-022" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA22","type":"percent","discount_value":15,"min_order_amount":100000,"max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-023: expired_at LB-1 — yesterday ($YESTERDAY) ===${NC}"
start_tc "FR17-BVA-023"
run_and_assert "FR17-BVA-023" "400" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"BVA23\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"${YESTERDAY}\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
end_tc

echo -e "${CYAN}=== FR17-BVA-024: expired_at LB — today ($TODAY) (valid) ===${NC}"
start_tc "FR17-BVA-024"
run_and_assert "FR17-BVA-024" "200" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"BVA24\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"${TODAY}\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "BVA24"
end_tc

echo -e "${CYAN}=== FR17-BVA-025: expired_at LB+1 — tomorrow ($TOMORROW) (valid) ===${NC}"
start_tc "FR17-BVA-025"
run_and_assert "FR17-BVA-025" "200" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"BVA25\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"${TOMORROW}\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "BVA25"
end_tc

echo -e "${CYAN}=== FR17-BVA-026: expired_at Nominal — 2027-12-31 (valid) ===${NC}"
start_tc "FR17-BVA-026"
run_and_assert "FR17-BVA-026" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA26","type":"percent","discount_value":15,"expired_at":"2027-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA26"
end_tc

echo -e "${CYAN}=== FR17-BVA-027: expired_at +α — 9999-12-31 (valid) ===${NC}"
start_tc "FR17-BVA-027"
run_and_assert "FR17-BVA-027" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA27","type":"percent","discount_value":15,"expired_at":"9999-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA27"
end_tc

# ─── BVA: code length ─────────────────────────────────────────────────────────

echo -e "${CYAN}=== FR17-BVA-028: code -α — empty string ===${NC}"
start_tc "FR17-BVA-028"
run_and_assert "FR17-BVA-028" "400" "POST" "/api/admin/coupons" "admin" \
  '{"code":"","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
end_tc

echo -e "${CYAN}=== FR17-BVA-029: code LB — 1 character 'A' (valid) ===${NC}"
start_tc "FR17-BVA-029"
run_and_assert "FR17-BVA-029" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"A","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "A"
end_tc

echo -e "${CYAN}=== FR17-BVA-030: code LB+1 — 2 characters 'AB' (valid) ===${NC}"
start_tc "FR17-BVA-030"
run_and_assert "FR17-BVA-030" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"AB","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "AB"
end_tc

echo -e "${CYAN}=== FR17-BVA-031: code Nominal — 8 characters 'BVA31' (valid) ===${NC}"
start_tc "FR17-BVA-031"
run_and_assert "FR17-BVA-031" "200" "POST" "/api/admin/coupons" "admin" \
  '{"code":"BVA31","type":"percent","discount_value":15,"expired_at":"2099-12-31","min_order_amount":100000,"max_uses_per_user":1}'
teardown_coupon_by_code "BVA31"
end_tc

# Generate 49-char and 50-char and 51-char and 300-char code strings
CODE_49=$(python3 -c "print('A'*49)")
CODE_50=$(python3 -c "print('A'*50)")
CODE_51=$(python3 -c "print('A'*51)")
CODE_300=$(python3 -c "print('A'*300)")

echo -e "${CYAN}=== FR17-BVA-032: code UB-1 — 49 chars (valid) ===${NC}"
start_tc "FR17-BVA-032"
run_and_assert "FR17-BVA-032" "200" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"${CODE_49}\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"2099-12-31\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "${CODE_49}"
end_tc

echo -e "${CYAN}=== FR17-BVA-033: code UB — 50 chars (valid) ===${NC}"
start_tc "FR17-BVA-033"
run_and_assert "FR17-BVA-033" "200" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"${CODE_50}\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"2099-12-31\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "${CODE_50}"
end_tc

echo -e "${CYAN}=== FR17-BVA-034: code UB+1 — 51 chars (flag if accepted) ===${NC}"
start_tc "FR17-BVA-034"
run_and_assert "FR17-BVA-034" "400" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"${CODE_51}\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"2099-12-31\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "${CODE_51}"
end_tc

echo -e "${CYAN}=== FR17-BVA-035: code +α — 300 chars (flag behavior) ===${NC}"
start_tc "FR17-BVA-035"
run_and_assert "FR17-BVA-035" "400" "POST" "/api/admin/coupons" "admin" \
  "{\"code\":\"${CODE_300}\",\"type\":\"percent\",\"discount_value\":15,\"expired_at\":\"2099-12-31\",\"min_order_amount\":100000,\"max_uses_per_user\":1}"
teardown_coupon_by_code "${CODE_300}"
end_tc

# =============================================================================
# FINAL SUMMARY
# =============================================================================
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD} FR-17 TEST RESULTS — AUTOMATED CHECKS${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
printf "  %-22s %-30s %-30s %s\n" "TC ID" "Expected" "Actual" "Status"
echo "  ──────────────────────────────────────────────────────────────────────"
for row in "${SUMMARY_ROWS[@]}"; do
  IFS='|' read -r S ID DESC EXP ACT <<< "$row"
  if [[ "$S" == "PASS" ]]; then
    C="$GREEN"
  elif [[ "$S" == "SKIP" ]]; then
    C="$YELLOW"
  else
    C="$RED"
  fi
  printf "  ${C}%-22s %-30s %-30s %s${NC}\n" \
    "${ID:0:22}" "${EXP:0:30}" "${ACT:0:30}" "$S"
done
echo "  ──────────────────────────────────────────────────────────────────────"
echo -e "  ${BOLD}TOTAL (automated): ${GREEN}${PASS} PASS${NC} | ${RED}${FAIL} FAIL${NC} | ${YELLOW}${SKIP} SKIP${NC}"
echo ""
echo -e "${YELLOW}  Still requires manual / DOM testing:${NC}"
echo -e "    MANUAL : FR17-EP-003 → open http://localhost:5174 (Admin UI, XSS check)"
echo -e "    DOM    : FR17-EP-006 → paste scripts/curl/FR17-dom-checks.js into DevTools Console"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Response JSON files saved to: $RESP_DIR/"
echo "Paste the summary block above into Phase B prompt."
